// src/api/beatPlanService.ts

// --- INTERFACE DEFINITIONS ---

// For the four summary cards at the top
export interface BeatPlanStats {
  totalPlans: number;
  activeRoutes: number;
  assignedEmployees: number;
  totalShops: number;
}

// For a single row in the "All Beat Plans" table
export interface BeatPlan {
  id: string; // Keep ID as string as generated by crypto.randomUUID()
  serial: string;
  employeeName: string;
  employeeRole: string;
  employeeImageUrl: string;
  planName: string;
  dateAssigned: string;
  shopsCount: number;
  status: 'active' | 'pending';
  // --- ADDED employeeId for editing convenience ---
  employeeId?: number; // Store the original ID for pre-selecting in edit form
}

// Main interface for all data on the page
export interface FullBeatPlanData {
  stats: BeatPlanStats;
  beatPlans: BeatPlan[];
}

// --- Interface for the "create" function payload ---
export interface NewBeatPlanPayload {
  employeeId: string;
  planName: string;
  date: Date | null;
  shopsCount: number;
}

// --- NEW: Interface for the "update" function payload ---
export interface UpdateBeatPlanPayload {
  employeeId: string;
  planName: string;
  date: Date | null;
  shopsCount: number;
  // Add status if you allow editing it
  // status?: 'active' | 'pending';
}


// --- MOCK DATA GENERATION (Now our "Database") ---

const employeesData = [
  { id: 1, name: 'Jason Price', designation: 'Admin', email: 'janick_parisian@yahoo.com', imageUrl: 'https://i.pravatar.cc/150?u=jason' },
  { id: 2, name: 'Jukkoe Sisao', designation: 'CEO', email: 'sibyl_koey@hotmail.com', imageUrl: 'https://i.pravatar.cc/150?u=jukkoe' },
  { id: 3, name: 'Harriet King', designation: 'CTO', email: 'nadia_block@hotmail.com', imageUrl: 'https://i.pravatar.cc/150?u=harrietk' },
  { id: 4, name: 'Lenora Benson', designation: 'Lead', email: 'feil.wallace@kunde.us', imageUrl: 'https://i.pravatar.cc/150?u=lenora' },
  { id: 5, name: 'Olivia Reese', designation: 'Strategist', email: 'kemmer.hattie@cremin.us', imageUrl: 'https://i.pravatar.cc/150?u=olivia' },
  { id: 6, name: 'Bertha Valdez', designation: 'Digital Marketer', email: 'loraine.koelpin@tromp.io', imageUrl: 'https://i.pravatar.cc/150?u=bertha' },
  { id: 7, name: 'Harriett Payne', designation: 'CEO', email: 'nunnie_west@estrella.tv', imageUrl: 'https://i.pravatar.cc/150?u=harriettp' },
  { id: 8, name: 'George Bryant', designation: 'Social Media', email: 'delmer.kling@gmail.com', imageUrl: 'https://i.pravatar.cc/150?u=george' },
  { id: 9, name: 'Lily French', designation: 'Strategist', email: 'lucienne.herman@hotmail.com', imageUrl: 'https://i.pravatar.cc/150?u=lily' },
  { id: 10, name: 'Howard Adkins', designation: 'CEO', email: 'wiegand.leonor@herman.us', imageUrl: 'https://i.pravatar.cc/150?u=howard' },
  { id: 11, name: 'Earl Bowman', designation: 'Digital Marketer', email: 'waino_ankeny@nicolette.tv', imageUrl: 'https://i.pravatar.cc/150?u=earl' },
  { id: 12, name: 'Patrick Padilla', designation: 'Social Media', email: 'octavia.nienow@gleichner.net', imageUrl: 'https://i.pravatar.cc/150?u=patrick' },
  { id: 13, name: 'John Doe', designation: 'Developer', email: 'john.doe@example.com', imageUrl: 'https://i.pravatar.cc/150?u=john' },
  { id: 14, name: 'Jane Smith', designation: 'Designer', email: 'jane.smith@example.com', imageUrl: 'https://i.pravatar.cc/150?u=jane' },
];

// This function creates the mock data for the table
const generateMockBeatPlans = (): BeatPlan[] => {
  const planTypes = ['Urban Blitz', 'Suburban Sweep', 'Metro Connect', 'Downtown Drive', 'Westside Route'];

  return employeesData.map((employee, index) => {
    // Generate a random date within the last 30 days
    const date = new Date();
    date.setDate(date.getDate() - (index * 2 + 1));
    const dateAssigned = date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });

    return {
      id: crypto.randomUUID(),
      serial: `BP${(index + 1).toString().padStart(3, '0')}`,
      employeeName: employee.name,
      employeeRole: employee.designation,
      employeeImageUrl: employee.imageUrl,
      planName: `${planTypes[index % planTypes.length]} #${index + 1}`,
      dateAssigned: dateAssigned,
      shopsCount: Math.floor(Math.random() * 10) + 2, // Random number of shops between 2 and 11
      status: index % 3 === 0 ? 'pending' : 'active', // Alternate status for variety
      employeeId: employee.id // Store the employee ID
    };
  });
};

// --- This is now our persistent mock database ---
let mockBeatPlanDB: BeatPlan[] = generateMockBeatPlans();


// --- MOCK API FETCH FUNCTIONS ---

/**
 * Fetches all beat plan data.
 */
export const getBeatPlanData = async (): Promise<FullBeatPlanData> => {
  // Simulate a network delay
  await new Promise(resolve => setTimeout(resolve, 1000));

  const mockData: FullBeatPlanData = {
    stats: {
      totalPlans: mockBeatPlanDB.length,
      activeRoutes: mockBeatPlanDB.filter(plan => plan.status === 'active').length,
      assignedEmployees: new Set(mockBeatPlanDB.map(p => p.employeeName)).size,
      totalShops: mockBeatPlanDB.reduce((sum, plan) => sum + plan.shopsCount, 0),
    },
    beatPlans: mockBeatPlanDB,
  };

  if (Math.random() > 0.95) {
    throw new Error("Failed to fetch Beat Plan data from the server.");
  }

  return mockData;
};

/**
 * --- Fetches the list of employees for the dropdown ---
 */
export const getBeatPlanEmployees = async () => {
  await new Promise(resolve => setTimeout(resolve, 300));
  // Return only id and name for the dropdown
  return employeesData.map(e => ({ id: e.id, name: e.name }));
}

/**
 * --- Creates a new beat plan and adds it to our mock DB ---
 */
export const createBeatPlan = async (payload: NewBeatPlanPayload): Promise<BeatPlan> => {
  // Simulate a network delay for creation
  await new Promise(resolve => setTimeout(resolve, 500));

  // Find the full employee details from the ID
  const employee = employeesData.find(e => e.id === parseInt(payload.employeeId));
  if (!employee) {
    throw new Error("Invalid employee ID");
  }

  const dateAssigned = (payload.date || new Date()).toLocaleDateString('en-US', {
    month: 'short', day: 'numeric', year: 'numeric'
  });

  // Create the new plan object
  const newPlan: BeatPlan = {
    id: crypto.randomUUID(),
    serial: `BP${(mockBeatPlanDB.length + 1).toString().padStart(3, '0')}`,
    employeeName: employee.name,
    employeeRole: employee.designation,
    employeeImageUrl: employee.imageUrl,
    planName: payload.planName || 'Unnamed Plan',
    dateAssigned: dateAssigned,
    shopsCount: payload.shopsCount,
    status: 'pending', // New plans always start as pending
    employeeId: employee.id // Store employee ID
  };

  // Add the new plan to the top of our "database"
  mockBeatPlanDB.unshift(newPlan);

  return newPlan;
};

// --- NEW: Function to get details for one plan ---
export const getBeatPlanDetails = async (planId: string): Promise<BeatPlan | undefined> => {
  console.log('Fetching details for mock plan ID:', planId);
  await new Promise(resolve => setTimeout(resolve, 400));
  // Find the plan in our mock DB
  const plan = mockBeatPlanDB.find(p => p.id === planId);
  if (!plan) {
    // Simulate not found
    console.error(`Beat plan with ID ${planId} not found.`);
    // throw new Error(`Beat plan with ID ${planId} not found.`); // Or throw error
    return undefined;
  }
  // In a real app, you would also fetch the assigned shops list associated with this plan ID
  console.log('Found plan details:', plan);
  return plan;
  // Real API:
  // const res = await api.get(`/beat-plans/${planId}`);
  // return res.data;
};

// --- NEW: Function to update a plan ---
export const updateBeatPlan = async (planId: string, payload: UpdateBeatPlanPayload): Promise<BeatPlan> => {
  console.log('Updating mock plan ID:', planId, 'with payload:', payload);
  await new Promise(resolve => setTimeout(resolve, 500));

  const planIndex = mockBeatPlanDB.findIndex(p => p.id === planId);
  if (planIndex === -1) {
    throw new Error(`Beat plan with ID ${planId} not found for update.`);
  }

  // Find full employee details
  const employee = employeesData.find(e => e.id === parseInt(payload.employeeId));
  if (!employee) {
    throw new Error("Invalid employee ID during update");
  }

  const dateAssigned = (payload.date || new Date()).toLocaleDateString('en-US', {
    month: 'short', day: 'numeric', year: 'numeric'
  });

  // Update the plan in our mock DB
  const updatedPlan: BeatPlan = {
    ...mockBeatPlanDB[planIndex], // Keep existing ID, serial, status etc.
    employeeName: employee.name,
    employeeRole: employee.designation,
    employeeImageUrl: employee.imageUrl,
    planName: payload.planName,
    dateAssigned: dateAssigned,
    shopsCount: payload.shopsCount,
    employeeId: employee.id // Update employee ID
    // Update status if needed from payload
    // status: payload.status || mockBeatPlanDB[planIndex].status,
  };

  mockBeatPlanDB[planIndex] = updatedPlan;
  console.log('Updated plan in DB:', updatedPlan);

  return updatedPlan;
  // Real API:
  // const res = await api.put(`/beat-plans/${planId}`, payload);
  // return res.data;
};